### ISSUE TITLE
AttributeError: 'bob.learn.em.GMMStats' object has no attribute 'copy'

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.bio.video#2]
I am trying to run an experiment with `bob.bio.video` and a `gmm` algorithm and I am seeing this error:
```
<Job: 4 (1281753) [1-32:1] - 'project'> | q_1day : failure (1) -- 'antispoofing.experiment/bin/verify.py' -vv -d 'replay-licit' -p 'bob.bio.video.preprocessor.Wrapper(bob
.bio.face.preprocessor.TanTriggs(bob.bio.face.preprocessor.FaceCrop(cropped_image_size=(80,64),cropped_positions={"topleft":(0,0),"bottomright":(80,64)})))' -e 'bob.bio.video.extractor.Wrapper("dct-blocks")' -a 
'bob.bio.video.algorithm.Wrapper("gmm")' -s 'replay-licit' --groups 'dev' 'eval' --grid 'demanding' -I 'bob.bio.base' 'bob.bio.video' 'bob.bio.face' --sub-task 'project' 
Array Job 1 (helvetix10) :
bob.bio.base@2016-05-17 19:58:48,292 -- INFO: - Projection: splitting of index range (0, 10)
bob.bio.base@2016-05-17 19:58:48,293 -- INFO: - Projection: projecting 10 features from directory '/idiap_temp/amohammadi/replay/replay-licit/./extracted' to directory '/idiap_temp/amohammadi/replay/replay-licit
/./projected'
--------------------
bob.bio.base@2016-05-17 19:58:40,133 -- WARNING: Under the desired name 'demanding', there are multiple entry points defined, we return the first one: ['bob.bio.base.config.grid.demanding', 'bob.bio.spear.config
.grid.demanding']
bob.bio.base@2016-05-17 19:58:51,275 -- ERROR: During the execution, an exception was raised: 'bob.learn.em.GMMStats' object has no attribute 'copy'
Traceback (most recent call last):
  File "antispoofing.experiment/bin/verify.py", line 29, in <module>
    sys.exit(bob.bio.base.script.verify.main())
  File "/idiap/bob-stable/py27/local/lib/python2.7/site-packages/bob/bio/base/script/verify.py", line 435, in main
    verify(args, command_line_parameters)
  File "/idiap/bob-stable/py27/local/lib/python2.7/site-packages/bob/bio/base/script/verify.py", line 382, in verify
    if not execute(args):
  File "/idiap/bob-stable/py27/local/lib/python2.7/site-packages/bob/bio/base/script/verify.py", line 287, in execute
    force = args.force)
  File "/idiap/bob-stable/py27/local/lib/python2.7/site-packages/bob/bio/base/tools/algorithm.py", line 116, in project
    projected = algorithm.project(feature)
  File "antispoofing.experiment/src/bob.bio.video/bob/bio/video/algorithm/Wrapper.py", line 127, in project
    features = projected if isinstance(projected, (list,tuple)) else projected.copy()
AttributeError: 'bob.learn.em.GMMStats' object has no attribute 'copy'
```

**Comment by tiagofrepereira2012** [comment]
I guess this project wasn't well tested with GMM Based systems since for most of the algorithms the projected features are `numpy array`.
For our implementation of GMM Based systems, the statistics of the GMM (`GMMStats`) are the projected features.

I don't know what to do in this case.
If you do this dirty patch, it works?:
```
projected if isinstance(projected, (list,tuple, bob.learn.em.GMMStats)) else projected.copy()
```

**Comment by 183amir** [comment]
The question is why is it copying `numpy.array`s which are pointers in `python` and not copying `list` and `tuple`s while they are also pointers in `python`.

**Comment by tiagofrepereira2012** [comment]
I don't know.

**Comment by 183amir** [comment]
The code is very confusing for me. It saving `bob.learn.em.GMMStats` as projected features and reading them in the same way but when they are loaded it checks if they are `numpy.array`s and they are!
I am talking about using `bob.bio.gmm` with `bob.bio.base` here, forgetting `bob.bio.video` for now.

It is projecting the features here: https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/algorithm.py#L130 and saving them in here: https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/algorithm.py#L141 using this function: https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/utils/io.py#L61

Reading them back here: https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/algorithm.py#L274 using this function: https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/algorithm/GMM.py#L193

(up until now everything is `bob.learn.em.GMMStats`)

And then, using the projected features here: https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/algorithm.py#L276 using this function: https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/algorithm/GMM.py#L205 which checks the features to be `numpy.array`s here: https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/algorithm/GMM.py#L88

( where apparently they are `numpy.array`s because I assume the code is working.)
What am I missing here?

**Comment by 183amir** [comment]
Ok I got that part. It is because this: https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/algorithm/GMM.py#L47 is False, so the features are read not project features.
So now I am back to my original question, why are we copying the projected features here?

**Comment by tiagofrepereira2012** [comment]
Just to complement your last question.
For the GMM system, the GMM projected features (`GMMStats`) are used **only** for the linear scoring (http://pythonhosted.org/bob.learn.em/py_api.html#bob.learn.em.linear_scoring).

About the copy of the numpy arrays, again, I don't know.

**Comment by 183amir** [comment]
So I have three suggestions: one is to check if the instance has a `copy` attribute:
```python
features = projected if isinstance(projected, (list,tuple)) or not hasattr(projected, 'copy') else projected.copy()
```
One is to skip copying: 
```python
features = projected
```
One is to change it to: 
```python
features = projected if isinstance(projected, (list,tuple)) else type(projected)(projected)
```

**Comment by siebenkopf** [comment]
To answer your question, why we copy: In the old facereclib, we were re-using objects inside our functions, and do not create new ones. Usually, this is fine as all of the objects are saved in a separate file, after they were created. 
However, for the video extension this didn't work, and I had a hard time to figure out what was going on. When we have several frames that are processed and stored into **the same** object, now we have to copy them as we write them all together into one HDF5 file.

Now, as far as I know, this behavior of reusing data has been stopped, so I think we should be fine without copying at all. But first, let me double-check if this is true, e.g., in bob.bio.base, bob.bio.face, bob.bio.gmm, bob.bio.spear and bob.bio.csu

**Comment by siebenkopf** [comment]
I have checked all of these packages, and it should be fine to remove the copy all-together. Particularly, for GMM projection:
https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/algorithm/GMM.py#L176
a new GMMStats object is created for each feature and, thus, it does not need to be copied. Only for some cases in the IVector class, there is internal memory returned:
https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/algorithm/IVector.py#L327
but this is not critical for us, as the models are not stored in a FrameContainer.

So, I will take care of that and remove the copying. Thanks for the report.

**Comment by siebenkopf** [comment]
In fact, this was the only surviving location, where the data was copied. All other places have been corrected before already.
P.S. There has been a reason, why lists where not copied, but I don't remember anymore. I assume that lists have always been created newly, and they have never been stored as internal values. Hence, there was no need to copy them before putting them into a FrameContainer.

**Comment by 183amir** [comment]
Thanks Manuel.
